# Generated by Django 4.2.3 on 2023-07-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.month'),
        ),
    ]
