# Generated by Django 4.2.3 on 2023-07-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0002_rename_name_category_type_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='month',
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetApp.accountinfo'),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetApp.accountinfo'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.month'),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.month'),
        ),
    ]
