# Generated by Django 4.2.3 on 2023-07-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0003_month_rename_type_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
    ]
