# Generated by Django 4.2.3 on 2023-07-07 16:00

import django.core.validators
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0004_rename_category_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=timezone.now().date()),
),
    ]
