# Generated by Django 4.2.3 on 2023-07-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0005_alter_expense_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='day',
        ),
    ]
