# Generated by Django 4.2.3 on 2023-07-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0006_rename_date_expense_day'),
    ]

    operations = [
    ]
