# Generated by Django 4.2.3 on 2023-07-07 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0007_auto_20230707_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='month',
        ),
        migrations.AlterField(
            model_name='expense',
            name='day',
            field=models.DateField(default=datetime.date(2023, 7, 7)),
        ),
    ]
